Repository cyder/SyncPod-Android, pull requests merged in 2018-05, with the labels that each got.

#247 v2.0.0
  app/build.gradle
Labels: wait for review

#250 lib versionを上げる
  app/build.gradle
  app/src/main/kotlin/com/cyder/android/syncpod/view/activity/SearchVideoActivity.kt
  app/src/main/kotlin/com/cyder/android/syncpod/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/ChatFragment.kt
  app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/PlayListFragment.kt
  app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/RoomInfoFragment.kt
Labels: new-architecture, wait for review

#253 roomに入れないバグを倒す
  app/src/main/kotlin/com/cyder/android/syncpod/di/NetworkModule.kt
Labels: new-architecture, wait for review

#255 検索できるようにする
  app/src/main/kotlin/com/cyder/android/syncpod/viewmodel/SearchVideoActivityViewModel.kt
  app/src/main/res/layout/activity_search_video.xml
Labels: new-architecture, wait for review

#266 ストリームを流すタイミングを調整
  app/src/main/kotlin/com/cyder/android/syncpod/repository/ChatDataRepository.kt
  app/src/main/kotlin/com/cyder/android/syncpod/websocket/SyncPodWsApiImpl.kt
Labels: bug, review complete

#263 APILevel 19以下で起動すらできない問題
  app/src/main/kotlin/com/cyder/android/syncpod/BaseApplication.kt
Labels: new-architecture, wait for review

#261 public roomを指定できるようにする．
  app/src/main/kotlin/com/cyder/android/syncpod/api/mapper/RoomDataMapper.kt
  app/src/main/kotlin/com/cyder/android/syncpod/api/request/CreateRoom.kt
  app/src/main/kotlin/com/cyder/android/syncpod/api/response/Room.kt
  app/src/main/kotlin/com/cyder/android/syncpod/model/Room.kt
  app/src/main/kotlin/com/cyder/android/syncpod/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/android/syncpod/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/android/syncpod/util/CustomBinder.kt
  app/src/main/kotlin/com/cyder/android/syncpod/viewmodel/CreateRoomActivityViewModel.kt
  app/src/main/res/layout/activity_create_room.xml
  app/src/main/res/values/strings.xml
Labels: wait for review

#264 人気ルームの一覧を作る
  app/src/main/kotlin/com/cyder/android/syncpod/api/SyncPodApi.kt
  app/src/main/kotlin/com/cyder/android/syncpod/api/response/Response.kt
  app/src/main/kotlin/com/cyder/android/syncpod/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/android/syncpod/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/android/syncpod/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/android/syncpod/viewmodel/TopActivityViewModel.kt
  app/src/main/res/layout/activity_top.xml
  app/src/main/res/values/strings.xml
Labels: wait for review

#268 チャットが２行以上になると、最後までスクロールされないバグ修正
  app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/ChatFragment.kt
Labels: bug, wait for review

#274 公開ルーム設定デザイン
  app/src/main/kotlin/com/cyder/android/syncpod/view/activity/CreateRoomActivity.kt
  app/src/main/kotlin/com/cyder/android/syncpod/viewmodel/CreateRoomActivityViewModel.kt
  app/src/main/res/layout/activity_create_room.xml
  app/src/main/res/layout/spinner_item_with_description.xml
  app/src/main/res/values/strings.xml
Labels: wait for review

#277 v2.1.0
  app/build.gradle
Labels: wait for review
