Repository cyder/SyncPod-Android, pull requests merged in 2018-03, with the labels that each got.

#177 アイコンを設定する
  app/src/main/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: review complete

#159 topactivityをつくる
  app/build.gradle
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/mapper/RoomDataMapper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/mapper/UserDataMapper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/mapper/VideoDataMapper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/response/Video.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Room.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/User.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Video.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomBinder.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/adapter/ArrayAdapter.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/adapter/BindingHolder.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/adapter/ObservableListAdapter.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
  app/src/main/res/layout/activity_top.xml
  app/src/main/res/layout/item_room.xml
Labels: new-architecture, wait for review

#179 roomの作成(UI)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/CreateRoomActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
  app/src/main/res/layout/activity_create_room.xml
Labels: new-architecture, wait for review

#181 ログイン後に戻るボタンを押すと白い画面が出るバグを修正
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/MainActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
Labels: wait for review
