Repository cyder/SyncPod-Android, pull requests merged in 2018-04, with the labels that each got.

#180 ログインミスったときのメッセージをいい感じにする
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
Labels: new-architecture, wait for review

#185 tokenをRoomRepositoryの引数にする
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
Labels: new-architecture, wait for review

#187 roomを作る・roomに入る．
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/request/CreateRoom.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/NetworkModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/RoomActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
  app/src/main/res/layout/activity_room.xml
  app/src/main/res/layout/item_room.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: new-architecture, review complete

#191 最近入室した部屋がちらつかないようにした
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Room.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
Labels: new-architecture, wait for review

#192 Update android studio
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  gradle/wrapper/gradle-wrapper.jar
Labels: new-architecture, wait for review

#189 利用規約を追加
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomBinder.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomInverseMethod.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: new-architecture, wait for review

#198 URLから入室できるようにする
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignInActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignUpActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SplashActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SplashActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
Labels: new-architecture, wait for review

#201 roomを作るときのエラーハンドリング
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/Exceptions.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/CreateRoomActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignInActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignUpActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SplashActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
Labels: new-architecture, wait for review

#205 動画のプログレスバーを表示する
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/VideoFragmentViewModel.kt
  app/src/main/res/layout/fragment_video.xml
Labels: new-architecture, wait for review

#206 ビデオの表示非表示の切り替え
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/BaseActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SplashActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/VideoFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/WelcomeActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/base/ActivityViewModel.kt
  app/src/main/res/layout/activity_room.xml
Labels: new-architecture, wait for review

#207 tablyoutとその他fragmentを実装
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/FragmentComponent.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomBinder.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/RoomActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/PlayListFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/RoomInfoFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/PlayListFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
  app/src/main/res/layout/activity_room.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_playlist.xml
  app/src/main/res/layout/fragment_roominfo.xml
Labels: new-architecture, wait for review

#210 apiのアドレスを変更する
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/NetworkModule.kt
Labels: new-architecture, wait for review

#212 roomでの処理（logic）
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
Labels: new-architecture, wait for review

#211 動画の検索（logic)
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/mapper/VideoDataMapper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/response/SearchResponse.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/YouTubeDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/YouTubeRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/Exceptions.kt
Labels: new-architecture, wait for review

#214 room情報タブ表示
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/RoomActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/RoomInfoFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ShareCompatCallback.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/UserViewModel.kt
  app/src/main/res/layout/fragment_roominfo.xml
  app/src/main/res/layout/item_user.xml
Labels: new-architecture, wait for review

#217 悪質ユーザー報告フォーム(UI & Logic)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserReportDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserReportRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/UserReportActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/UserReportActivityViewModel.kt
  app/src/main/res/layout/activity_user_report.xml
  app/src/main/res/layout/fragment_roominfo.xml
  app/src/main/res/values/strings.xml
Labels: new-architecture, wait for review

#222 メモリ解放時にアプリが落ちるバグを修正
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/ChatDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
Labels: wait for review

#219 動画の検索まわり
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/mapper/VideoDataMapper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Video.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/YouTubeDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomBinder.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SearchVideoActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/PlayListFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SearchVideoActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/VideoViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
  app/src/main/res/layout/activity_search_video.xml
  app/src/main/res/layout/fragment_playlist.xml
  app/src/main/res/layout/item_video.xml
Labels: new-architecture, wait for review

#220 指定したユーザを強制退出させる
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/RoomInfoFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ButtonInterface.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/UserViewModel.kt
  app/src/main/res/layout/item_user.xml
  app/src/main/res/values/strings.xml
Labels: new-architecture, wait for review

#234 動画検索フォームがからの時に落ちるバグを修正
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SearchVideoActivityViewModel.kt
Labels: bug, new-architecture, wait for review

#227 強制退出を受けた時に自ら退出する
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/Data.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
  app/src/main/res/values/strings.xml
Labels: new-architecture, wait for review

#226 チャットを見たり送ったり
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Chat.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/ChatDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/ChatRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/Data.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApi.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/mapper/ChatDataMapper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/response/Chat.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/item_chat.xml
Labels: new-architecture, wait for review

#232 ViewModelからsyncPodWsApiを消し去る
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/UserViewModel.kt
Labels: new-architecture, wait for review

#231 cueに入ってる時に動画のタイトルが表示されないバグを修正
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/PlayListFragmentViewModel.kt
Labels: new-architecture, wait for review

#236 チャットフォームをフラグメント化する
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/FragmentComponent.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomBinder.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/RoomActivity.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFormFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/animation.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFormFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
  app/src/main/res/layout/activity_room.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_form.xml
Labels: new-architecture, wait for review

#240 チャットのスクロールを固定する
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFragment.kt
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
  app/src/main/res/layout/fragment_chat.xml
Labels: new-architecture, wait for review

#242 キーボードの左右キーでタブが移動しないようにした
  app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/components/WithoutKeyEventViewPager.kt
  app/src/main/res/layout/activity_room.xml
Labels: new-architecture, wait for review

#246 productionbuildでコケるのを直す
  app/proguard-rules.pro
Labels: new-architecture, wait for review
